# Generated by Django 2.2.13 on 2020-11-05 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_campany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Campany')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=50)),
                ('campany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Campany')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Division')),
            ],
        ),
    ]
