# Generated by Django 2.2.13 on 2020-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201108_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subjectDetail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
