# Generated by Django 2.2.13 on 2020-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201108_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='app_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
