# Generated by Django 2.2.13 on 2020-11-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_order_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subjectName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
