# Generated by Django 2.2.13 on 2020-11-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_order_requestsection_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requestSection_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='requestSection_E',
            field=models.BooleanField(default=False),
        ),
    ]
