# Generated by Django 2.2.13 on 2020-11-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201109_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
