# Generated by Django 2.2.13 on 2020-11-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_order_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expenseItems',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
