# Generated by Django 2.2.13 on 2020-11-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201109_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='safeContact_start',
            field=models.BooleanField(default=False),
        ),
    ]
