# Generated by Django 2.2.13 on 2020-11-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_order_safecontact_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='safeContact_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeContact_intermediate',
            field=models.BooleanField(default=False),
        ),
    ]
