# Generated by Django 2.2.13 on 2020-11-09 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_order_campany'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Division'),
        ),
        migrations.AddField(
            model_name='order',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Process'),
        ),
    ]
