# Generated by Django 2.2.13 on 2020-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201109_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='safeWitness_always',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeWitness_disassembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeWitness_intermediate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeWitness_start',
            field=models.BooleanField(default=False),
        ),
    ]
