# Generated by Django 2.2.13 on 2020-11-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201109_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='safeEnvironment_dust',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeEnvironment_height',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeEnvironment_pit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeEnvironment_updown',
            field=models.BooleanField(default=False),
        ),
    ]
