# Generated by Django 2.2.13 on 2020-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201109_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='safeEnvironment_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
