# Generated by Django 2.2.13 on 2020-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_order_safeenvironment_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='safeHazardous_ASH3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeHazardous_CO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeHazardous_CO2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeHazardous_H2S',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeHazardous_SO2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeHazardous_SO3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeHazardous_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
