# Generated by Django 2.2.13 on 2020-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20201109_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='safeProtecter_acid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeProtecter_earplug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeProtecter_fallPrevention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeProtecter_gloves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeProtecter_helmet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeProtecter_shoes',
            field=models.BooleanField(default=False),
        ),
    ]
