# Generated by Django 2.2.13 on 2020-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20201109_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='leagalConfimation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeAspect_liquid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeAspect_oil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeAspect_remaining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeAspect_waste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='safeNotices',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
