# Generated by Django 2.2.13 on 2020-11-10 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20201109_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failuretype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='failuretype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Failuretype'),
        ),
    ]
