# Generated by Django 2.2.13 on 2020-11-10 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20201110_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='expenseItems',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.ExpenseItems'),
        ),
    ]
