# Generated by Django 2.2.13 on 2020-11-13 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20201113_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('codeM', models.CharField(max_length=20)),
                ('campany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Campany')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Division')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Process')),
            ],
        ),
    ]
