# Generated by Django 2.2.13 on 2020-12-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_subprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='app_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='wishEnd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='wishStart_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
