# Generated by Django 2.2.13 on 2020-12-22 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20201222_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='neoProcess',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Subprocess'),
        ),
    ]
