# Generated by Django 2.2.13 on 2021-01-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
