# Generated by Django 2.2.13 on 2021-01-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_place_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='tag',
        ),
    ]
