# Generated by Django 2.2.13 on 2021-01-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_remove_place_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whmeter',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Place'),
        ),
    ]
