from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail,name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/list/', views.post_list2, name='post_list2'),
    path('post/Campany/', views.post_campany_list, name='post_campany_list'),
    path('post/Campany/<int:pk>/', views.post_campany_detail,name='post_campany_detail'),
    path('post/Campany/new/', views.post_campany_new, name='post_campany_new'),
    path('post/Campany/<int:pk>/edit', views.post_campany_edit, name='post_campany_edit'),
    path('post/master/', views.master_select, name='master_select'),
    path('post/Division/', views.post_division_list, name='post_division_list'),
    path('post/Division/<int:pk>/', views.post_division_detail,name='post_division_detail'),
    path('post/Division/new/', views.post_division_new, name='post_division_new'),
    path('post/Division/<int:pk>/edit', views.post_division_edit, name='post_division_edit'),
    path('post/Process/', views.post_process_list, name='post_process_list'),
    path('post/Process/<int:pk>/', views.post_process_detail,name='post_process_detail'),
    path('post/Process/new/', views.post_process_new, name='post_process_new'),
    path('post/Process/<int:pk>/edit', views.post_process_edit, name='post_process_edit'),
    path('post/Subprocess/', views.post_subprocess_list, name='post_subprocess_list'),
    path('post/Subprocess/<int:pk>/', views.post_subprocess_detail,name='post_subprocess_detail'),
    path('post/Subprocess/new/', views.post_subprocess_new, name='post_subprocess_new'),
    path('post/Subprocess/<int:pk>/edit', views.post_subprocess_edit, name='post_subprocess_edit'),
    path('post/Order/', views.post_order_list, name='post_order_list'),
    path('post/Order/<int:pk>/', views.post_order_detail,name='post_order_detail'),
    path('post/Order/new/', views.post_order_new, name='post_order_new'),
    path('post/Order/<int:pk>/edit', views.post_order_edit, name='post_order_edit'),
    path('post/Process/new2/', views.ProcessCreate.as_view(), name='processCreate'),
    path('api/division/get/', views.ajax_get_category, name='ajax_get_category'),

]
